<?php

## FILE GENERATED BY MAGRATHEA.
## SHOULD NOT BE CHANGED MANUALLY

class MagratheaImageBase extends MagratheaModel implements iMagratheaModel {

	public $id, $name, $filename, $extension, $width, $height, $file_type, $size;
	protected $lazyLoad = true;

	public function __construct( $id=0 ){ 
		$this->Start();
		if( !empty($id) ){
			$pk = $this->dbPk;
			$this->$pk = $id;
			$this->GetById($id);
		}
	}
	public function Start(){
		$this->dbTable = "magrathea_images";
		$this->dbPk = "id";
		$this->dbValues["id"] = "int";
		$this->dbValues["name"] = "string";
		$this->dbValues["filename"] = "string";
		$this->dbValues["extension"] = "string";
		$this->dbValues["width"] = "int";
		$this->dbValues["height"] = "int";
		$this->dbValues["file_type"] = "int";
		$this->dbValues["size"] = "int";

	}

	// >>> relations:

}

class MagratheaImageControlBase extends MagratheaModelControl {
	protected static $modelName = "MagratheaImage";
	protected static $dbTable = "magrathea_images";
}
?>