#!/bin/bash
clear

NEW_SITE="$1"

echo -e "Nice to have you here! Welcome to Magrathea!\n"
echo -e "We are now going through the proccess of creating the $NEW_SITE project! Let's go!\n\n"
sleep 1

echo -e "\n\nCreating folder..."
mkdir "$NEW_SITE"
cd "$NEW_SITE"
mkdir site
cd ..
echo -e "DONE!\n"
sleep 1

echo -e "\n\nCopying content..."
cp Magrathea/magrathea.tgz "$NEW_SITE"/site/magrathea.tgz
cp Magrathea/smarty.tgz "$NEW_SITE"/site/smarty.tgz
cp Magrathea/magrathea_admin.tgz "$NEW_SITE"/site/magrathea_admin.tgz
cd "$NEW_SITE"/site
echo -e "DONE!\n"
sleep 1

echo -e "\nExtracting files..."
tar xzvf magrathea.tgz Magrathea/
rm -rf magrathea.tgz
mv magrathea_admin.tgz Magrathea/magrathea_admin.tgz
echo -e "DONE!\n"
sleep 1

echo -e "\nSetting up initial config..."
chmod 777 Magrathea/configs
PWD=$(pwd)
cat <<EOF >Magrathea/configs/magrathea.conf
# generated by Magrathea at 2013-01-19 06:26:23

[general]
	compress_js = "false"
	compress_css = "false"
	use_environment = "dev"
	time_zone = "America/Sao_Paulo"

[dev]
	db_host = "127.0.0.1"
	db_name = "database"
	db_user = "root"
	db_pass = "password"
	site_path = "$PWD/"
	magrathea_path = "$PWD/Magrathea/"
EOF
echo -e "DONE!\n"
sleep 1

echo -e "\n\nCreating folder structure..."
mkdir app
chmod 777 app
mv Magrathea/index/* app/
rm -rf Magrathea/index
cd app
chmod 777 javascript
chmod 777 javascript/_compressed
chmod 777 css
chmod 777 css/_compressed
mkdir Models
chmod 777 Models
mkdir admin
chmod 777 admin
mkdir inc
chmod 777 inc
cat <<EOF >inc/global.php
<?php

	require(__DIR__."/../../Magrathea/LOAD.php");
	include(__DIR__."/../../Smarty/Smarty.class.php");
	
	\$Smarty = new Smarty;
	\$Smarty->config_load("site.conf");
	
	\$Smarty = new Smarty;
	\$Smarty->template_dir = $site_path."Views/";
	\$Smarty->compile_dir  = $site_path."Views/_compiled";
	\$Smarty->config_dir   = $site_path."Views/configs";
	\$Smarty->cache_dir    = $site_path."Views/_cache";

?>
EOF
chmod 777 inc/global.php
mkdir images
chmod 777 Models
mkdir Views
chmod 777 Views
cd Views
mkdir _compiled
chmod 777 _compiled
cat <<EOF >_compiled/readme.txt
this folder is for use of Smarty framework!
EOF
mkdir _cache
chmod 777 _cache
cat <<EOF >_cache/readme.txt
this folder is for use of Smarty framework!
EOF
mkdir configs
chmod 777 configs
cat <<EOF >configs/site.conf
#global:
siteName="$NEW_SITE"
siteDomain="" 
EOF
chmod 777 configs/site.conf
cd ..
echo -e "DONE!\n"
sleep 1

echo -e "\n\nInstalling Smarty..."
cd ..
tar xzvf smarty.tgz Smarty/
rm -rf smarty.tgz
echo -e "DONE!\n"
sleep 1





#compress code: tar -pvczf magrathea.tgz Magrathea/

#extract code: tar xzvf magrathea.tgz Magrathea/

