<?php

require ("admin_load.php");
	
	$mconfig = new MagratheaConfigFile();
	$mconfig->setPath(MagratheaConfig::Instance()->GetConfigFromDefault("site_path"));
	$mconfig->setFile("/../configs/magrathea_objects.conf");
	$objdata = $mconfig->getConfig();

	$env = MagratheaConfig::Instance()->GetConfig("general/use_environment");
	$site_path = MagratheaConfig::Instance()->GetConfig($env."/site_path");
	$models_dir = $site_path."/Models";
	$base_dir = $models_dir."/Base";

	echo "<br/><pre>";
	if( !is_dir($base_dir) ){
		mkdir($base_dir);
	}
	foreach( $objdata as $object => $data ){
		if( $object == "relations" ) continue;
		echo "- Object: ".$object."\n\t";
		$obj_fields = array();
		foreach($data as $key => $item){
			if( substr($key, -6) == "_alias" ){
				$field_name = substr($key, 0, -6);
				if( $field_name == "created_at" || $field_name == "updated_at" ) continue;
				array_push($obj_fields, $field_name);
			}
		}

		$relations = array();
		$relations = GetRelationsByObject($object);
		$relations_properties = "";
		$relations_functions = "";
		$relations_autoload = array();
		foreach($relations as $rel){
			$relations_properties .= "\t\t\$this->relations[\"properties\"][\"".$rel["rel_property"]."\"] = null;\n";
			$relations_properties .= "\t\t\$this->relations[\"methods\"][\"".$rel["rel_property"]."\"] = \"".$rel["rel_method"]."\";\n";
			$relations_properties .= "\t\t\$this->relations[\"lazyload\"][\"".$rel["rel_property"]."\"] = \"".($rel["rel_lazyload"] == 1 ? "true" : "false")."\";\n";
			
			$relations_functions .= "\tpublic function ".$rel["rel_method"]."(){\n";
			$relations_functions .= "\t\tif(\$this->relations[\"properties\"][\"".$rel["rel_property"]."\"] != null) return \$this->relations[\"properties\"][\"".$rel["rel_property"]."\"];\n";
			if( $rel["rel_type"] == "belongs_to" ) {
				$relations_functions .= "\t\t\$this->relations[\"properties\"][\"".$rel["rel_property"]."\"] = new ".$rel["rel_object"]."(\$this->".$rel["rel_field"].");\n";
			} else if ( $rel["rel_type"] == "has_many" ) {
				$relations_functions .= "\t\t\$pk = \$this->dbPk;\n";
				$relations_functions .= "\t\t\$this->relations[\"properties\"][\"".$rel["rel_property"]."\"] = ".$rel["rel_object"]."ControlBase::GetWhere(array(\"".$rel["rel_field"]."\" => \$this->\$pk));\n";
			}
			$relations_functions .= "\t\treturn \$this->relations[\"properties\"][\"".$rel["rel_property"]."\"];\n";
			$relations_functions .= "\t}\n";

			if( $rel["rel_type"] == "belongs_to" ) {
				$obj_var = "\$".strtolower($rel["rel_property"]);
				$relations_functions .= "\tpublic function Set".$rel["rel_property"]."(".$obj_var."){\n";
				$relations_functions .= "\t\t\$this->relations[\"properties\"][\"".$rel["rel_property"]."\"] = ".$obj_var.";\n";
				$relations_functions .= "\t\t\$this->".$rel["rel_field"]." = ".$obj_var."->GetID();\n";
				$relations_functions .= "\t\treturn \$this;\n";
				$relations_functions .= "\t}\n";
			}

			if($rel["rel_autoload"] == 1){
				array_push($relations_autoload, "\"".$rel["rel_property"]."\" => \"".$rel["rel_field"]."\"");
			}

		} // close foreach relations
	
		$code = "<?php\n\n";
		$code .= "## FILE GENERATED BY MAGRATHEA.\n## SHOULD NOT BE CHANGED MANUALLY\n\n";

		$code .= "class ".$object."Base extends MagratheaModel implements iMagratheaModel {\n\n";
		
		$code .= "\tpublic \$".implode(", $", $obj_fields).";\n";
		$code .= "\tpublic \$created_at, \$updated_at;\n";
		$code .= "\tpublic \$dbPk;\n";
		$code .= "\tprotected \$autoload = ".(count($relations_autoload) == 0 ? "null" : "array(".implode(", ", $relations_autoload).")").";\n\n";
		
		$code .= "\tpublic function __construct( ".( ($data["db_pk"]) ? " \$".$data["db_pk"]."=0 " : "\$id=0" )." ){ \n";
			$code .= "\t\t\$this->MagratheaStart();\n";
			if($data["db_pk"]){
				$code .= "\t\tif( !empty(\$".$data["db_pk"].") ){\n";
					$code .= "\t\t\t\$pk = \$this->dbPk;\n";
					$code .= "\t\t\t\$this->\$pk = \$".$data["db_pk"].";\n";
					$code .= "\t\t\t\$this->GetById(\$".$data["db_pk"].");\n";
				$code .= "\t\t}\n";
			}
		$code .= "\t}\n";
		$code .= "\tpublic function MagratheaStart(){\n";
			$code .= "\t\t\$this->dbTable = \"".$data["table_name"]."\";\n";
			$code .= "\t\t\$this->dbPk = \"".$data["db_pk"]."\";\n";
			foreach($obj_fields as $f){
				$code .= "\t\t\$this->dbValues[\"".$f."\"] = \"".$data[$f."_type"]."\";\n";
				if( !empty($data[$f."_alias"]) )
					$code .= "\t\t\$this->dbAlias[\"".$data[$f."_alias"]."\"] = \"".$f."\";\n";
			}
			
			$code .= "\n".$relations_properties;
			$code .= "\n";
			$code .= "\t\t\$this->dbAlias[\"created_at\"] =  \"datetime\";\n";
			$code .= "\t\t\$this->dbAlias[\"updated_at\"] =  \"datetime\";\n";
		$code .= "\t}\n\n";

		$code .= "\t// >>> relations:\n".$relations_functions."\n";

		$code .= "}\n\n";
		
		$code .= "class ".$object."ControlBase extends MagratheaModelControl {\n";
			$code .= "\tprotected static \$modelName = \"".$object."\";\n";
			$code .= "\tprotected static \$dbTable = \"".$data["table_name"]."\";\n";
		$code .= "}\n";		

		$code .= "?>";

		$base_filename = $object."Base.php";
		if( writeFile($base_dir, $base_filename, $code) ){
			echo "\t".$base_filename." was successfully created! =)\n\n";
		} else {
			echo "\tOh, boy... there was an error trying to write ".$base_filename."... =(\n\t";
			echo "\tPlease, assure that ".$base_dir." is writable by PHP!\n\n";
		}
		
		$filename = $object.".php";
		if( !file_exists($models_dir."/".$filename) ){
			$code2 = "<?php\n\n";
			$code2 .= "include(__DIR__.\"/Base/".$base_filename."\");\n\n";

			$code2 .= "class ".$object." extends ".$object."Base {\n";
			$code2 .= "\t// your code goes here!\n";
			$code2 .= "}\n\n";
			
			$code2 .= "class ".$object."Control extends ".$object."ControlBase {\n";
			$code2 .= "\t// and here!\n";
			$code2 .= "}\n\n";
			
			$code2 .= "?>";
			if( writeFile($models_dir, $filename, $code2) ){
				chmod($models_dir."/".$filename, 0777);
				echo "\t".$filename." was created as well. This way, things gets much easier for you! =)\n\n";
			}
		}

	} // close for each Object
	echo "</pre>";

function writeFile($filepath, $filename, $content){
	if(file_exists($filepath."/".$filename)){
		unlink($filepath."/".$filename);
	}
	if (!$handle = @fopen($filepath."/".$filename, 'w')) { 
		return false; 
	} 
	if (!fwrite($handle, $content)) { 
		return false; 
	} 
	fclose($handle); 
	return true; 
}

?>
