<?php include("inc/header.php"); ?>

	<div class="container main_container">
		<h1>Config File</h1>
		<p>
			The project configuration files can be found at the <code>configs</code> folder.<br/>
		</p>
		<h2>magrathea.conf</h2>
		<p>
			This is the main configuration file, and it's required.<br/>
			You may find some structure just like this:
			<pre class="prettyprint linenums">
// generated by Magrathea at [...]

[general]
	use_environment = "default"
	time_zone = "America/Sao_Paulo"

[default]
	db_host = "127.0.0.1"
	db_name = "teste"
	db_user = "test_user"
	db_pass = "test_pass"
	site_path = "/Users/Sites/mywebsite/app/"
	magrathea_path = "/Users/Sites/mywebsite/Magrathea/"
	compress_js = "false"
	compress_css = "false"
	time_zone = "America/Sao_Paulo"
	testThis = "test_ok"

[another_config]
	db_host = "127.0.0.2"
	db_name = "production"
	db_user = "production_user"
	db_pass = "production_pass"
	site_path = "/etc/mywebsite/app/"
	magrathea_path = "/etc/mywebsite/Magrathea/"
	compress_js = "true"
	compress_css = "true"
	time_zone = "America/Sao_Paulo"
	testThis = "test_not_ok"
			</pre>
		<br/>
		If you can see the first comment line, it means that the file was generated by Magrathea system.<br/>
		It's possible to edit this config file inside <a href="admin_php.php">admin.php</a>, so you can see the last time it was edited.<br/><br/> 
		The <code>general</code> section is an internal control of the Magrathea config file.<br/>
		After that, you can have as many different sections as you want. This will allow you to create a section for development, a secion for homolog, a section for production, a section for your mother, your dog etc.<br/>
		You will be able to define the environment that will be used in the <code>use_environment</code> option inside the general section.<br/>
		</p>


		<h2>magrathea_objects.conf</h2>
		<p>
			<div class="alert alert-error">
				This file should not be editted manually! It's a configuration file for objects management from <a href="admin_php.php">admin.php</a>.
			</div>
			<code>magrathea_objects.conf</code> will save the data for your objects and relations. Some of it structure may be copied if you are reusing some parts of the system, but you souldn't have to touch it. Really.
		</p>



		<h2>Your own config file</h2>
		You can also create your own configuration file and ask <em>Magrathea</em> to read its data for you.<br/>
		More about it you can find in <a href="class-MagratheaConfigFile.html.php">MagratheaConfig</a> class.
	</div>

<?php include("inc/footer.php"); ?>