<?php include('inc/header.php'); ?>
	<div id="left">
	<div id="menu">
		


		<div id="groups">
		</div>


		<div id="elements">
			<h3>Classes</h3>
			<ul>
				<li><a href="class-Magdb.html">Magdb</a></li>
				<li><a href="class-MagratheaAdmin.html">MagratheaAdmin</a></li>
				<li><a href="class-MagratheaCompressor.html">MagratheaCompressor</a></li>
				<li><a href="class-MagratheaConfig.html">MagratheaConfig</a></li>
				<li><a href="class-MagratheaConfigFile.html">MagratheaConfigFile</a></li>
				<li><a href="class-MagratheaController.html">MagratheaController</a></li>
				<li><a href="class-MagratheaDebugger.html">MagratheaDebugger</a></li>
				<li><a href="class-MagratheaEmail.html">MagratheaEmail</a></li>
				<li><a href="class-MagratheaImage.html">MagratheaImage</a></li>
				<li><a href="class-MagratheaImageBase.html">MagratheaImageBase</a></li>
				<li><a href="class-MagratheaImageControl.html">MagratheaImageControl</a></li>
				<li><a href="class-MagratheaImageControlBase.html">MagratheaImageControlBase</a></li>
				<li><a href="class-MagratheaLogger.html">MagratheaLogger</a></li>
				<li><a href="class-MagratheaModel.html">MagratheaModel</a></li>
				<li><a href="class-MagratheaModelControl.html">MagratheaModelControl</a></li>
				<li><a href="class-MagratheaQuery.html">MagratheaQuery</a></li>
				<li><a href="class-MagratheaQueryDelete.html">MagratheaQueryDelete</a></li>
				<li><a href="class-MagratheaQueryInsert.html">MagratheaQueryInsert</a></li>
				<li><a href="class-MagratheaServer.html">MagratheaServer</a></li>
				<li><a href="class-MagratheaView.html">MagratheaView</a></li>
				<li><a href="class-PhpClosure.html">PhpClosure</a></li>
				<li><a href="class-UploadHandler.html">UploadHandler</a></li>
			</ul>

			<h3>Interfaces</h3>
			<ul>
				<li><a href="class-Magdb.html">Magdb</a></li>
				<li><a href="class-MagratheaAdmin.html">MagratheaAdmin</a></li>
				<li><a href="class-MagratheaCompressor.html">MagratheaCompressor</a></li>
				<li><a href="class-MagratheaConfig.html">MagratheaConfig</a></li>
				<li><a href="class-MagratheaConfigFile.html">MagratheaConfigFile</a></li>
				<li><a href="class-MagratheaController.html">MagratheaController</a></li>
				<li><a href="class-MagratheaDebugger.html">MagratheaDebugger</a></li>
				<li><a href="class-MagratheaEmail.html">MagratheaEmail</a></li>
				<li><a href="class-MagratheaImage.html">MagratheaImage</a></li>
				<li><a href="class-MagratheaImageBase.html">MagratheaImageBase</a></li>
				<li><a href="class-MagratheaImageControl.html">MagratheaImageControl</a></li>
				<li><a href="class-MagratheaImageControlBase.html">MagratheaImageControlBase</a></li>
				<li><a href="class-MagratheaLogger.html">MagratheaLogger</a></li>
				<li><a href="class-MagratheaModel.html">MagratheaModel</a></li>
				<li><a href="class-MagratheaModelControl.html">MagratheaModelControl</a></li>
				<li><a href="class-MagratheaQuery.html">MagratheaQuery</a></li>
				<li><a href="class-MagratheaQueryDelete.html">MagratheaQueryDelete</a></li>
				<li><a href="class-MagratheaQueryInsert.html">MagratheaQueryInsert</a></li>
				<li><a href="class-MagratheaServer.html">MagratheaServer</a></li>
				<li><a href="class-MagratheaView.html">MagratheaView</a></li>
				<li><a href="class-PhpClosure.html">PhpClosure</a></li>
				<li><a href="class-UploadHandler.html">UploadHandler</a></li>
			</ul>


			<h3>Exceptions</h3>
			<ul>
				<li><a href="class-MagratheaConfigException.html">MagratheaConfigException</a></li>
				<li><a href="class-MagratheaControllerException.html">MagratheaControllerException</a></li>
				<li><a href="class-MagratheaDBException.html">MagratheaDBException</a></li>
				<li><a href="class-MagratheaException.html">MagratheaException</a></li>
				<li><a href="class-MagratheaModelException.html">MagratheaModelException</a></li>
				<li class="active"><a href="class-MagratheaViewException.html">MagratheaViewException</a></li>
			</ul>


			<h3>Functions</h3>
			<ul>
				<li><a href="function-createDirInApps.html">createDirInApps</a></li>
				<li><a href="function-Debug.html">Debug</a></li>
				<li><a href="function-magrathea_getTypesArr.html">magrathea_getTypesArr</a></li>
				<li><a href="function-magrathea_printFields.html">magrathea_printFields</a></li>
				<li><a href="function-mascara.html">mascara</a></li>
				<li><a href="function-nice_p_r.html">nice_p_r</a></li>
				<li><a href="function-now.html">now</a></li>
				<li class="active"><a href="function-p_r.html">p_r</a></li>
			</ul>
		</div>
	</div>
</div>

<div id="splitter"></div>

<div id="right">
	<div id="rightInner">
<pre id="source"><code><span id="1" class="l"><a href="#1"> 1 </a><span class="xlang">&lt;?php</span>
</span><span id="2" class="l"><a href="#2"> 2 </a>
</span><span id="3" class="l"><a href="#3"> 3 </a><span class="php-comment">## FILE GENERATED BY MAGRATHEA.</span>
</span><span id="4" class="l"><a href="#4"> 4 </a><span class="php-comment">## SHOULD NOT BE CHANGED MANUALLY</span>
</span><span id="5" class="l"><a href="#5"> 5 </a>
</span><span id="6" class="l"><a href="#6"> 6 </a><span class="php-keyword1">class</span> MagratheaImageBase <span class="php-keyword1">extends</span> MagratheaModel <span class="php-keyword1">implements</span> iMagratheaModel {
</span><span id="7" class="l"><a href="#7"> 7 </a>
</span><span id="8" class="l"><a href="#8"> 8 </a>    <span class="php-keyword1">public</span> <span class="php-var">$id</span>, <span class="php-var">$name</span>, <span class="php-var">$filename</span>, <span class="php-var">$extension</span>, <span class="php-var">$width</span>, <span class="php-var">$height</span>, <span class="php-var">$file_type</span>, <span class="php-var">$size</span>;
</span><span id="9" class="l"><a href="#9"> 9 </a>    <span class="php-keyword1">protected</span> <span class="php-var">$lazyLoad</span> = <span class="php-keyword1">true</span>;
</span><span id="10" class="l"><a href="#10">10 </a>
</span><span id="11" class="l"><a href="#11">11 </a>    <span class="php-keyword1">public</span> <span class="php-keyword1">function</span> __construct( <span class="php-var">$id</span>=<span class="php-num">0</span> ){ 
</span><span id="12" class="l"><a href="#12">12 </a>        <span class="php-var">$this</span>-&gt;Start();
</span><span id="13" class="l"><a href="#13">13 </a>        <span class="php-keyword1">if</span>( !<span class="php-keyword1">empty</span>(<span class="php-var">$id</span>) ){
</span><span id="14" class="l"><a href="#14">14 </a>            <span class="php-var">$pk</span> = <span class="php-var">$this</span>-&gt;dbPk;
</span><span id="15" class="l"><a href="#15">15 </a>            <span class="php-var">$this</span>-&gt;<span class="php-var">$pk</span> = <span class="php-var">$id</span>;
</span><span id="16" class="l"><a href="#16">16 </a>            <span class="php-var">$this</span>-&gt;GetById(<span class="php-var">$id</span>);
</span><span id="17" class="l"><a href="#17">17 </a>        }
</span><span id="18" class="l"><a href="#18">18 </a>    }
</span><span id="19" class="l"><a href="#19">19 </a>    <span class="php-keyword1">public</span> <span class="php-keyword1">function</span> Start(){
</span><span id="20" class="l"><a href="#20">20 </a>        <span class="php-var">$this</span>-&gt;dbTable = <span class="php-quote">&quot;magrathea_images&quot;</span>;
</span><span id="21" class="l"><a href="#21">21 </a>        <span class="php-var">$this</span>-&gt;dbPk = <span class="php-quote">&quot;id&quot;</span>;
</span><span id="22" class="l"><a href="#22">22 </a>        <span class="php-var">$this</span>-&gt;dbValues[<span class="php-quote">&quot;id&quot;</span>] = <span class="php-quote">&quot;int&quot;</span>;
</span><span id="23" class="l"><a href="#23">23 </a>        <span class="php-var">$this</span>-&gt;dbValues[<span class="php-quote">&quot;name&quot;</span>] = <span class="php-quote">&quot;string&quot;</span>;
</span><span id="24" class="l"><a href="#24">24 </a>        <span class="php-var">$this</span>-&gt;dbValues[<span class="php-quote">&quot;filename&quot;</span>] = <span class="php-quote">&quot;string&quot;</span>;
</span><span id="25" class="l"><a href="#25">25 </a>        <span class="php-var">$this</span>-&gt;dbValues[<span class="php-quote">&quot;extension&quot;</span>] = <span class="php-quote">&quot;string&quot;</span>;
</span><span id="26" class="l"><a href="#26">26 </a>        <span class="php-var">$this</span>-&gt;dbValues[<span class="php-quote">&quot;width&quot;</span>] = <span class="php-quote">&quot;int&quot;</span>;
</span><span id="27" class="l"><a href="#27">27 </a>        <span class="php-var">$this</span>-&gt;dbValues[<span class="php-quote">&quot;height&quot;</span>] = <span class="php-quote">&quot;int&quot;</span>;
</span><span id="28" class="l"><a href="#28">28 </a>        <span class="php-var">$this</span>-&gt;dbValues[<span class="php-quote">&quot;file_type&quot;</span>] = <span class="php-quote">&quot;int&quot;</span>;
</span><span id="29" class="l"><a href="#29">29 </a>        <span class="php-var">$this</span>-&gt;dbValues[<span class="php-quote">&quot;size&quot;</span>] = <span class="php-quote">&quot;int&quot;</span>;
</span><span id="30" class="l"><a href="#30">30 </a>
</span><span id="31" class="l"><a href="#31">31 </a>    }
</span><span id="32" class="l"><a href="#32">32 </a>
</span><span id="33" class="l"><a href="#33">33 </a>    <span class="php-comment">// &gt;&gt;&gt; relations:</span>
</span><span id="34" class="l"><a href="#34">34 </a>
</span><span id="35" class="l"><a href="#35">35 </a>}
</span><span id="36" class="l"><a href="#36">36 </a>
</span><span id="37" class="l"><a href="#37">37 </a><span class="php-keyword1">class</span> MagratheaImageControlBase <span class="php-keyword1">extends</span> MagratheaModelControl {
</span><span id="38" class="l"><a href="#38">38 </a>    <span class="php-keyword1">protected</span> <span class="php-keyword1">static</span> <span class="php-var">$modelName</span> = <span class="php-quote">&quot;MagratheaImage&quot;</span>;
</span><span id="39" class="l"><a href="#39">39 </a>    <span class="php-keyword1">protected</span> <span class="php-keyword1">static</span> <span class="php-var">$dbTable</span> = <span class="php-quote">&quot;magrathea_images&quot;</span>;
</span><span id="40" class="l"><a href="#40">40 </a>}
</span><span id="41" class="l"><a href="#41">41 </a><span class="xlang">?&gt;</span></span></code></pre>
	</div>

	<?php include('inc/footer.php'); ?>
